package com.company.propertyprice.model;

// Generated May 6, 2014 5:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PropertySale generated by hbm2java
 */
public class PropertySale implements java.io.Serializable {

	private int id;
	private Address address;
	private double price;
	private Date dateOfSale;
	private boolean fullMarketPrice;
	private Date dateCreated;
	private Date dateUpdated;
	private String pprUrl;
	private String propertySize;
	private String description;
	private boolean vatExclusive;
	private String status;

	public PropertySale() {
	}

	public PropertySale(int id, Address address, double price, Date dateOfSale,
			boolean fullMarketPrice, String pprUrl) {
		this.id = id;
		this.address = address;
		this.price = price;
		this.dateOfSale = dateOfSale;
		this.fullMarketPrice = fullMarketPrice;
		this.dateCreated = new Date();
		this.dateUpdated = new Date();
		this.pprUrl = pprUrl;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Date getDateOfSale() {
		return this.dateOfSale;
	}

	public void setDateOfSale(Date dateOfSale) {
		this.dateOfSale = dateOfSale;
	}

	public boolean isFullMarketPrice() {
		return this.fullMarketPrice;
	}

	public void setFullMarketPrice(boolean fullMarketPrice) {
		this.fullMarketPrice = fullMarketPrice;
	}

	public String getPprUrl() {
		return this.pprUrl;
	}

	public void setPprUrl(String pprUrl) {
		this.pprUrl = pprUrl;
	}

	/**
	 * @return the dateCreated
	 */
	public Date getDateCreated() {
		return dateCreated;
	}

	/**
	 * @param dateCreated the dateCreated to set
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * @return the dateUpdated
	 */
	public Date getDateUpdated() {
		return dateUpdated;
	}

	/**
	 * @param dateUpdated the dateUpdated to set
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	/**
	 * @return the propertySize
	 */
	public String getPropertySize() {
		return propertySize;
	}

	/**
	 * @param propertySize the propertySize to set
	 */
	public void setPropertySize(String propertySize) {
		this.propertySize = propertySize;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the vatExclusive
	 */
	public boolean isVatExclusive() {
		return vatExclusive;
	}

	/**
	 * @param vatExclusive the vatExclusive to set
	 */
	public void setVatExclusive(boolean vatExclusive) {
		this.vatExclusive = vatExclusive;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
	    return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
	    this.status = status;
	}



	
}
