package com.company.propertyprice.model;

// Generated May 6, 2014 5:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PropertySale generated by hbm2java
 */
public class PropertySaleError implements java.io.Serializable {

	private int id;
	private String issue;
	private String pprUrl;
	private Date dateCreated;
	private Date dateUpdated;

	public PropertySaleError() {
	}

	public PropertySaleError(int id, String issue, String pprUrl) {
		this.id = id;
		this.issue = issue;
		this.pprUrl = pprUrl;
		this.dateCreated = new Date();
		this.dateUpdated = new Date();
	}

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the issue
	 */
	public String getIssue() {
		return issue;
	}

	/**
	 * @param issue the issue to set
	 */
	public void setIssue(String issue) {
		this.issue = issue;
	}

	/**
	 * @return the pprUrl
	 */
	public String getPprUrl() {
		return pprUrl;
	}

	/**
	 * @param pprUrl the pprUrl to set
	 */
	public void setPprUrl(String pprUrl) {
		this.pprUrl = pprUrl;
	}

	/**
	 * @return the dateCreated
	 */
	public Date getDateCreated() {
		return dateCreated;
	}

	/**
	 * @param dateCreated the dateCreated to set
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * @return the dateUpdated
	 */
	public Date getDateUpdated() {
		return dateUpdated;
	}

	/**
	 * @param dateUpdated the dateUpdated to set
	 */
	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

	
	
}
