package com.company.propertyprice.model;

// Generated May 6, 2014 5:18:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PropertySale generated by hbm2java
 */
public class PropertySaleUpdate implements java.io.Serializable {

	private int id;
	private Date dateCreated;
	private String pprUrl;

	public PropertySaleUpdate() {
	}

	public PropertySaleUpdate(int id, Address address, String pprUrl) {
		this.id = id;
		this.dateCreated = new Date();
		this.pprUrl = pprUrl;
	}

	/**
	 * @return the id
	 */
	public int getId() {
	    return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
	    this.id = id;
	}

	/**
	 * @return the dateCreated
	 */
	public Date getDateCreated() {
	    return dateCreated;
	}

	/**
	 * @param dateCreated the dateCreated to set
	 */
	public void setDateCreated(Date dateCreated) {
	    this.dateCreated = dateCreated;
	}

	/**
	 * @return the pprUrl
	 */
	public String getPprUrl() {
	    return pprUrl;
	}

	/**
	 * @param pprUrl the pprUrl to set
	 */
	public void setPprUrl(String pprUrl) {
	    this.pprUrl = pprUrl;
	}

}
